# Generated by Django 5.2 on 2025-10-05 20:31

import django.db.models.deletion
import django.utils.timezone
import sphinxdoc.validators
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('sphinxdoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
