# Generated by Django 5.2 on 2025-10-17 23:38

import django.core.validators
import django.utils.timezone
import sphinxdoc.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphinxdoc', '0002_index_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_column='project', max_length=100, verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used in the URL for the project. Must be unique.', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='repo',
            field=models.URLField(blank=True, db_column='repository', help_text='Project repository URL.', max_length=255, validators=[django.core.validators.URLValidator(schemes=['http', 'https', 'git'])], verbose_name='repository'),
        ),
        migrations.AddField(
            model_name='project',
            name='root',
            field=models.CharField(blank=True, help_text="Projects' root directory", max_length=255, validators=[sphinxdoc.validators.validate_relative_path]),
        ),
        migrations.RenameField(
            model_name='project',
            old_name='path',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='project',
            name='source',
            field=models.CharField(default='docs', help_text='Relative path containing ReStructured Text and the Sphinx configuration file, <tt>conf.py</tt> (Default: `docs/` ).', max_length=255, validators=[sphinxdoc.validators.validate_relative_path]),
        ),
        migrations.AddField(
            model_name='project',
            name='target',
            field=models.CharField(default='_build', help_text='Relative path containing Sphinx output (Default: `_build` )', max_length=255, validators=[sphinxdoc.validators.validate_relative_path]),
        ),
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='deleted',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
