# Generated by Django 5.2 on 2025-10-17 23:42

import django.core.validators
import django.utils.timezone
import sphinxdoc.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphinxdoc', '0003_modified_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='content',
            new_name='data',
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(db_column='title', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='document',
            name='data',
            field=models.TextField(verbose_name='content'),
        ),
    ]
